class_name ChunkManager extends Node

# Chunk Manager defines the order in which chunks are generated. It splits this task among the available threads.

# This determines if we use infinite word generation size or finite.
@export var finite_world: bool = false
# This is used to determine the size of the world in meters, if Infinite World Generation isn't 
# turned on.
@export var world_vector: int = 128
# Chunk Size doesn't include vertical height, since we likely will be using tall chunks.
@onready var chunk_size: int = Settings.chunk_size
@onready var chunk_height: int = Settings.chunk_height
@onready var skip_these_chunks = []
@onready var player_focus: BlockRay = $"../Player/Head/PlayerEyes/PlayerFocus"
@onready var player: CharacterBody3D = $"../Player"
@export var world_size: Vector3 = Vector3(world_vector, world_vector, world_vector)

# Cutoff defines how dense the random cubes are. Higher numbers equate to less density.
@export_range(-1, 1) var cutoff: float = 0.1
#@export var colors: Array[Color]
@export var block_types: Array[BlockType] = []
# We will get the random seed in the _ready() function.
@export var noise_seed: int = 0

var render_distance = Settings.chunk_render_distance
var random_generator = FastNoiseLite.new()
var number_of_chunks: Vector3
var kill_thread: bool = false

var loading_threads: Array = Settings.threads

var chunk_class = preload("res://chunk.tscn")
var chunks: Dictionary[Vector3i, Chunk] = {}
var block_colors: PackedColorArray = PackedColorArray()

# This is a boolean that we use to determine if a thread is stopped or not. We use it in thread_is_kill.
var kill: bool = false

# Signals
signal blocks_ready(block_types: Array) # This tells other scenes, like Player, when the ChunkManager
# is ready and has initialized all existing BlockTypes.

func _ready():
	# Uncomment this to make the world gen random. It's not currently, which can be helpful in testing.
	# Leaving this commented means the map will be the same every time you run the game.
	#random_generator.seed = randi()
	
	# This makes it so the Signal emission at the end of generate_chunks() doesn't fire until the
	# World script is loaded. If we don't have these lines, that signal emits before the connection
	# is made in World's script.
	await $"../".ready
	
	player.add_block.connect(self._on_add_block)
	player.remove_block.connect(self._on_remove_block)
	#var x = Chunk.atlas
	#var number_of_textures_in_atlas = Vector2((Chunk.atlas_size / Settings.texture_size), 1)
	
	var chunks_to_generate = []
	if finite_world == true:
		chunks_to_generate = generate_terrain_finite()
	else:
		chunks_to_generate = generate_terrain_infinite()
	
	multithreaded_terrain_generation(chunks_to_generate, loading_threads)
	# This lists every voxel (and its color) in the spawn chunk.
	
	# Tell other scenes we're ready
	EventBus.blocks_ready.emit(block_types)
	
	# This tells everybody when the Chunk Manager (I.E. this file) is ready
	EventBus.chunk_manager = self
	

func generate_terrain_finite():
	random_generator.noise_type = FastNoiseLite.TYPE_SIMPLEX
	random_generator.frequency = 0.003
	number_of_chunks = world_size / chunk_size

func generate_terrain_infinite():
	random_generator.noise_type = FastNoiseLite.TYPE_SIMPLEX
	random_generator.frequency = 0.003

	var chunk_queue = get_chunk_queue()
	var num_threads: int = loading_threads.size()
	var chunk_coordinates: Array = []
	
	for i in range(num_threads):
		chunk_coordinates.append([])
	
	for i in range(chunk_queue.size()):
		chunk_coordinates[i % num_threads].append(chunk_queue[i])    
	return chunk_coordinates

#2/2/2026: Generates concentric circlular rings, not a spiral. Appears to have no gaps or overlap.
# 2/23/26: Attempting to avoid generating multiple layers of chunks on top of each other. Since we're
# generating chunks per X, Y, and Z, this is using 3 passes to generate them. We just want X and Z.
# This was largely generated by AI. Refactor using real human brains.
#var y = 0
func get_chunk_queue():
	var chunk_queue = []
	# Changing the below to "range(0, render_distance+1)" will let this method generate the
	# spawnpoint. Keeping it at "range(1, render_distance+1)" leaves the spawnpoint to be generated
	# elsewhere so it can send a signal.
	for distance in range(1, render_distance + 1):
		# Generate all chunks within this ring (distance-1 < r <= distance)
		for x in range(-distance, distance + 1):
			for y in range(-distance, distance + 1):
				# Does this check for a chunk at 0,0? Is this just trying to avoid re-generating the spawn chunk?
				# Commenting it out appears to do nothing bad. For now.
				#if x == 0 and y == 0:
					#continue
			
				# Check if this chunk is in the current ring
				var current_ring = Vector2i(x, y).length()
				
				if current_ring > (distance - 1) and current_ring <= distance:
					chunk_queue.append(Vector3i(x, y, 0))
	return(chunk_queue)

# First, this checks the chunk to see if it needs to be skipped. If not, it goes to add_chunk_to_screen().
#func generate_a_chunk(x, y, z):
	#var position = Vector3i(x, y, z)
	#if skip_these_chunks.has(position):
		#print("Skipping existing chunk at ", position)
		#return

	# Generate the chunk otherwise. This function defines each chunk's properties before putting it onscreen.
	# This is also where we need to hook in to generate terrain per chunk.
	#else:
		#pass
		# This needs to be whatever function actually adds a chunk to the worldspace.
		# add_chunk_to_screen(x, y)

func generate_chunks(pos):
	var _voxels = []
	
	for chunk in pos:
		#print(chunk)
		if kill_thread == true:
			break
		var new_chunk = chunk_class.instantiate()
		#print("New chunk: ", new_chunk)
		new_chunk.position = Vector3i((chunk.x * chunk_size), (chunk.z * chunk_height), (chunk.y * chunk_size))
		#print("New chunk position: ", new_chunk.position)
		new_chunk.generate_data(chunk_size, chunk_height, random_generator, block_types)
		#print("New chunk data: ", new_chunk.voxels)
		new_chunk.generate_mesh()
		#print("Generated new chunk ", new_chunk)
		# This names each chunk after its coordinates. It divides each chunk's name by the chunk size,
		# so the second chunk to the left is "(-1, 0, 0)", instead of "(-32, 0, 0)".
		new_chunk.name = str((new_chunk.position as Vector3i)/Vector3i(chunk_size, chunk_size, chunk_size))
		# This returns the location and color of every voxel in the chunk. We should save this so it's accessible somehow.
		# print("New chunk: ", new_chunk.voxels)
		chunks[chunk] = new_chunk
		call_deferred("add_child", new_chunk)

func multithreaded_terrain_generation(chunks_by_thread, _number_of_threads):
	var spawn_point = [Vector3i(0, 0, 0)]
	generate_chunks(spawn_point)  # Generate spawn chunk first
	
	for i in range(chunks_by_thread.size()):
		if i < loading_threads.size() and not chunks_by_thread[i].is_empty():
			loading_threads[i].start(func(): generate_chunks(chunks_by_thread[i]))

func _on_add_block(_pos: Vector3i):
	var chunk = player_focus.get_collider() as Chunk
	#var _chunk_gloc = Vector3i(chunk.global_position)
#	var local_pos = player_focus.get_ray_hit().remove_position - Vector3i(chunk.global_position)
	var append_position = player_focus.get_ray_hit().add_position - Vector3i(chunk.global_position)
	#var color = chunk.voxels[local_pos]
	var selected_block = player.selected_block_type
	chunk.voxels[append_position] = selected_block
	#print(chunk.voxels[append_position].name)
	chunk.regenerate_mesh()
	
	# TODO: Add logic that prevents a voxel from being added to a chunk outside of the chunk's boundaries
	# Additionally, prevent adding chunks that would clip with the player. Or anything, really.

func _on_remove_block(_pos: Vector3i):
	var chunk = player_focus.get_collider() as Chunk
	var _chunk_gloc = Vector3i(chunk.global_position)
	var local_pos = player_focus.get_ray_hit().remove_position - Vector3i(chunk.global_position)
	
	if chunk.voxels.has(local_pos):
		chunk.voxels.erase(local_pos)
		chunk.regenerate_mesh()
	else:
		return

func get_voxel(pos: Vector3i):
	# Pos is currently the voxel's Global Position. We need the voxel's Local Position and return it.
	var chunk = player_focus.get_collider()
	var chunk_gloc = Vector3i(chunk.global_position)
	var chunk_x = int(floor(pos.x / Settings.chunk_size))
	var chunk_z = int(floor(pos.z / Settings.chunk_size))
	var chunk_key = "%d_%d" % [chunk_x, chunk_z]
	var local_pos = pos - chunk_gloc
	#print("Chunk key: %s, Local position: %s" % [chunk_key, local_pos])
	return {
		"chunk_key": chunk_key,
		"local_pos": local_pos
	}

func remove_chunk(chunk_position: Vector3i):
	if !chunks.has(chunk_position): return
	var chunk = chunks[chunk_position]
	chunks.erase(chunk_position)
	chunk.queue_free()

func create_chunk(chunk_position: Vector3i):
	# This function is used when modifying a chunk. It has to delete the old mesh and add a new one.
	remove_chunk(chunk_position)
	
	var chunk = chunk_class.instantiate() as Chunk
	chunk.chunk_data.SetSize(chunk_size)
	chunk.position = chunk_position
	chunks[chunk.position] = chunk
	
	return chunk

# This acts as a flag that should allow us to terminate threads almost instantly.
func thread_is_kill() -> bool:
	kill_thread = true
	return kill

func _exit_tree():
	for thread in loading_threads:
		thread.wait_to_finish()
