class_name Chunk
extends Node3D

# This Class defines the geometry of Voxels, how voxels are placed inside Chunks, and how Chunk
# meshes are optimized. We should probably split out Voxels into its own class.

# Following https://www.youtube.com/watch?v=Pfqfr3zFyKI

@export var tree_types: Array[TreeType]
@export var material: Material

# Transparent materials need their own mesh, partially because we have the Debug Rendering option that
# makes everything transparent. I don't know if removing that option would allow us to use just one mesh or not.
@export var transparent_material: Material

@onready var mesh_instance: MeshInstance3D = $TerrainMesh

var voxels: Dictionary[Vector3i, BlockType] = {}

# Dirty voxels are, as opposed to naturally generated voxels, ones that the player has added or removed.
# They will also include things like liquids that have flowed into neighboring blocks.
# We are keeping track of these and only saving them, so we don't have to save every voxel in a chunk.
# If we implement quarries, those chunks are going to have large save files, but everything else
# should be way smaller. We might be able to use some compression to shrink mostly empty chunks.
var dirty_voxels: Dictionary = {}
var number_of_textures_in_atlas: Vector2 = Vector2.ZERO

# Where should we store the world's seed, exactly? Maybe in world.tscn?
var world_seed: int = 0

#var surface_array: Array = []
var vertices = PackedVector3Array()
var normals = PackedVector3Array()
var uvs = PackedVector2Array()
var uv2s: PackedVector2Array = PackedVector2Array()

# Transparent geometry, such as for leaves, water, glass, etc.
# Apparently you need multiple meshes if some of your textures have transparencies.
var transparent_vertices = PackedVector3Array()
var transparent_normals = PackedVector3Array()
var transparent_uvs = PackedVector2Array()

# Stores the altitude of the first air block above the surface of each column.
# Can be used for spawning things like trees and structures without having to calculate each time.
var heightmap: Array = []

# Adding keys to each chunk so it can be referenced by filename
var chunks_key: Vector3i = Vector3i.ZERO

# For fixing axis flipping on chunk generation
var world_origin: Vector3i = Vector3i.ZERO

# For tuning cave generation
@export var big_cave_density: float = 0.05			# 0-1, higher = more caves
@export var big_cave_size: float = 0.15				# Lower = bigger caves
@export var long_cave_density: float = 0.05			# 0-1, higher = more caves
@export var long_cave_size: float = 0.15				# Lower = bigger caves
@export var cave_surface_margin: int = 10			# how many blocks from surface caves are suppressed
@export var cave_surface_reduction: float = 0.15	# how much rarer caves are near surface

# For Benchmarking
@export var benchmarking: bool = false
var face_time: int = 0

# For debug rendering
#@export var debug_transparent: bool = false

# These are implemented to make regenerating chunks multithreaded.
var is_rebuilding: bool = false
var regen_thread: Thread = Thread.new()
var regen_mutex: Mutex = Mutex.new()
var rebuild_count: int = 0

# This is to help address lag when adding or removing a block.
var needs_rebuild: bool = false

# For fixing freeze caused by all chunks being generated on the main thread
var was_generated_by_thread: bool = false
# Timing results, read by ChunkManager after generate_mesh() returns
var stat_generate_mesh_us: int = 0
var stat_add_face_us: int = 0
var stat_add_face_count: int = 0

func _process(_delta: float) -> void:
	if needs_rebuild and not is_rebuilding:
		needs_rebuild = false
		threaded_rebuild()

func _ready() -> void:
	# Skip this chunk if it's empty or was generated by worldgen already
	if voxels.is_empty():
		return
	if was_generated_by_thread:
		return
	commit_mesh()

func carve_caves(global_pos: Vector3, world_y: float, big_cave_noise: Noise, long_cave_noise: Noise, surface_factor: float) -> bool:
	# We currently have two types of cave systems: Big caves and Long caves. Big caves tend to be large open areas, long caves
	# tend to be long, noodly caves.
	var big_caves_a = big_cave_noise.get_noise_3d(
		global_pos.x * big_cave_size,
		world_y * big_cave_size,
		global_pos.z * big_cave_size)
	var big_caves_b = big_cave_noise.get_noise_3d(
		global_pos.x * big_cave_size + 100.0,
		world_y * big_cave_size,
		global_pos.z * big_cave_size + 100.0)
	var long_caves_a = long_cave_noise.get_noise_3d(
		global_pos.x * long_cave_size,
		world_y * long_cave_size,
		global_pos.z * long_cave_size)
	var long_caves_b = long_cave_noise.get_noise_3d(
		global_pos.x * long_cave_size + 100.0,
		world_y * long_cave_size,
		global_pos.z * long_cave_size + 100.0)
		
	var big_threshold = big_cave_density * surface_factor
	var long_threshold = long_cave_density * surface_factor
	
	if abs(big_caves_a) < big_threshold and abs(big_caves_b) < big_threshold:
		#print("Carving at y: ", world_y)
		return true
	if abs(long_caves_a) < long_threshold and abs(long_caves_b) < long_threshold:
		return true
	return false

func get_bedrock_height(global_pos: Vector3, heightmap_noise: Noise) -> int:
	var bedrock_noise = heightmap_noise.get_noise_2d(
		global_pos.x * 0.5,
		global_pos.z * 0.5)
	return int((bedrock_noise + 1) / 2 * 3) + 1

# This function determines the position of each block in a given chunk. I believe this is where we
# need to record the location of each block, perhaps in a dictionary?
func generate_data(chunk_size: int, chunk_height: int, heightmap_noise: Noise, big_cave_noise: Noise, long_cave_noise: Noise)  -> void:
	# Apply any cross-chunk structure blocks registered for this chunk
	var ccs_blocks: Array = EventBus.chunk_manager.claim_ccs(chunks_key)
	if not ccs_blocks.is_empty():
		print("Chunk ", chunks_key, " claimed ", ccs_blocks.size(), " CCS blocks")
	for entry in ccs_blocks:
		voxels[entry["world_pos"] - Vector3i(int(world_origin.x), int(world_origin.y), int(world_origin.z))] = entry["block"]
	
	# Define block types you'll need to refer to by name. Set them to 0 just in case something gets
	# messed up, then look for them by value.
	#var blocks = get_block_types(block_types)
	var bedrock = BlockRegistry.get_block("bedrock")
	var grass = BlockRegistry.get_block("grass")
	var dirt = BlockRegistry.get_block("dirt")
	var default_block = BlockRegistry.get_block(Settings.default_block)

	if bedrock == null or grass == null or dirt == null or default_block == null:
		print("WARNING: missing block types, skipping generation")
		return

	for x in range(chunk_size):
		for z in range(chunk_size):
			# Global XZ of this column
			var global_pos_x: float = world_origin.x + x # Needs to be a float because we use float math for the noise below.
			var global_pos_z: float = world_origin.z + z
	
			# This is the formula we use to generate the shape of our terrain. The three
			# get_noise_2ds act as 3 different octaves; the first generates large hills and valleys,
			# the second adds medium details, and the third adds fine detail.
			# The stuff on the ends of the lines ( +0.5, +0.25, etc) determine the steepness of these details.
			var rand: float = ((
				heightmap_noise.get_noise_2d(global_pos_x, global_pos_z) + 0.6 * 
				heightmap_noise.get_noise_2d(global_pos_x * 2, global_pos_z * 2) + 0.25 * 
				heightmap_noise.get_noise_2d(global_pos_x * 4, global_pos_z * 4)
				) / 1.75)
			
			const sea_level = Settings.sea_level
			const terrain_amplitude: int = 24
			
			# This is the surface height of this column.
			var surface_height: int = sea_level + int(rand * terrain_amplitude)
			
			# Dirt depth for this column
			var dirt_depth: int = int(
				heightmap_noise.get_noise_2d(
					global_pos_x * 0.3,
					global_pos_z * 0.3
					) * 1.5)
			
			# Bedrock depth for this column
			var bedrock_height: int = int((
					heightmap_noise.get_noise_2d(
					global_pos_x * 0.5,
					global_pos_z * 0.5
					) + 1 ) / 2.3) + 1
			
			for y in range(chunk_height):
				var world_y: int = int(world_origin.y) + y
			
				# Air, skip
				if world_y >= surface_height:
					continue # This might mess up trees and structures?
				
				var block_to_place = BlockType
				
				if world_y <= bedrock_height: # Bedrock layer
					block_to_place = bedrock
				elif world_y == surface_height - 1: # Surface block
					block_to_place = grass
				elif world_y >= surface_height - dirt_depth: # Dirt layer
					block_to_place = dirt
				else: block_to_place = default_block # Everything else is stone
				
				# Handling Caves; skip bedrock
				if block_to_place != bedrock:
					var surface_factor: float = clamp(
						float(surface_height - world_y) / cave_surface_margin,
						0.2, 1.0)
					if carve_caves(Vector3(global_pos_x, world_y, global_pos_z),
					world_y, big_cave_noise, long_cave_noise, surface_factor):
						continue
						
				voxels[Vector3i(x, y, z)] = block_to_place
				
	# Build heightmap after all voxels are placed
	heightmap.resize(chunk_size)
	for x in range(chunk_size):
		heightmap[x] = []
		heightmap[x].resize(chunk_size)
		for z in range(chunk_size):
			heightmap[x][z] = -1
			for y in range(chunk_height - 1, -1, -1):
				if voxels.has(Vector3i(x, y, z)):
					# Store global Y of the air block above this surface block
					heightmap[x][z] = int(world_origin.y) + y + 1
					break
	
	
	# Tree generation pass — runs after heightmap is built
	for x in range(chunk_size):
		for z in range(chunk_size):
			var surface_y: int = heightmap[x][z]
			if surface_y == -1:
				continue

			# Only place trees on grass blocks
			var surface_block_pos: Vector3i = Vector3i(x, surface_y - 1 - int(world_origin.y), z)
			if not voxels.has(surface_block_pos):
				continue
			if voxels[surface_block_pos] != BlockRegistry.get_block("grass"):
				continue

			var world_x: int = int(world_origin.x) + x
			var world_z: int = int(world_origin.z) + z

			if not TreeGenerator.should_place_tree(world_x, world_z, world_seed):
				continue

			# Pick species using weighted selection across all registered tree types
			var total_weight: int = 0
			for t in tree_types:
				total_weight += t.spawn_weight

			var species_hash: int = abs(hash(Vector3i(world_x, world_seed + 1, world_z)))
			var roll: int = species_hash % total_weight
			var chosen: TreeType = tree_types[0]
			var cumulative: int = 0
			for t in tree_types:
				cumulative += t.spawn_weight
				if roll < cumulative:
					chosen = t
					break

			var tree_blocks: Dictionary = TreeGenerator.generate_tree(
				chosen, surface_y, world_x, world_z,
				voxels, world_origin, chunk_size, chunk_height)

			if tree_blocks.is_empty():
				continue

			# Sort blocks into local (this chunk) and adjacent (neighboring chunks)
			for world_pos: Vector3i in tree_blocks:
				var local_pos: Vector3i = world_pos - Vector3i(int(world_origin.x), int(world_origin.y), int(world_origin.z))
				if local_pos.x >= 0 and local_pos.x < chunk_size and \
						local_pos.y >= 0 and local_pos.y < chunk_height and \
						local_pos.z >= 0 and local_pos.z < chunk_size:
					voxels[local_pos] = tree_blocks[world_pos]
				else:
					print("Sending to CCS: world_pos=", world_pos, " chunk position=", world_origin)
					EventBus.chunk_manager.register_ccs(world_pos, tree_blocks[world_pos])
			 
func generate_mesh() -> void:
	if voxels.is_empty(): return
	var start_time = Time.get_ticks_usec()
	var local_add_face_count: int = 0
	var local_add_face_total: int = 0
	
	# Opaque blocks use the GreedyMesh class
	GreedyMesh.mesh(voxels, vertices, normals, uvs, uv2s, number_of_textures_in_atlas)
	
	# Transparent blocks still use per-face for now.
	var t3 = Time.get_ticks_usec()
	for pos in voxels:
		var block_type = voxels[pos]
		if not block_type.is_transparent:
			continue
		if not should_hide_face(pos, Vector3i(pos.x, pos.y, pos.z + 1), block_type):
			add_face(Cube.Face.FRONT, pos, block_type)
		if not should_hide_face(pos, Vector3i(pos.x, pos.y, pos.z - 1), block_type):
			add_face(Cube.Face.BACK, pos, block_type)
		if not should_hide_face(pos, Vector3i(pos.x - 1, pos.y, pos.z), block_type):
			add_face(Cube.Face.LEFT, pos, block_type)
		if not should_hide_face(pos, Vector3i(pos.x + 1, pos.y, pos.z), block_type):
			add_face(Cube.Face.RIGHT, pos, block_type)
		if not should_hide_face(pos, Vector3i(pos.x, pos.y + 1, pos.z), block_type):
			add_face(Cube.Face.TOP, pos, block_type)
		if not should_hide_face(pos, Vector3i(pos.x, pos.y - 1, pos.z), block_type):
			add_face(Cube.Face.BOTTOM, pos, block_type)
		
	var t4 = Time.get_ticks_usec()
	if benchmarking == true:
		print("Voxel face creation: ", t4-t3, "ms")
		face_time = 0
	stat_generate_mesh_us = Time.get_ticks_usec() - start_time
	stat_add_face_us = local_add_face_total
	stat_add_face_count = local_add_face_count

func should_hide_face(pos: Vector3i, neighbor_pos: Vector3i, current_block: BlockType) -> bool:
	if not voxels.has(neighbor_pos):
		return false  # Skip faces with no neighbors
	var neighbor = voxels[neighbor_pos]
	# Cull only if neighbor is opaque, or if both blocks are the same transparent type
	if neighbor.is_transparent and not current_block.is_transparent:
		return false  # Don't cull if an opaque face touches a transparent face.
	if neighbor.is_transparent and current_block.is_transparent:
		return neighbor == current_block  # This culls the face ONLY if both blocks are the same.
	return true  # Neighbor is opaque,cull.

func add_face(face: Cube.Face, pos: Vector3i, block: BlockType) -> void:
	var t0: int
	if benchmarking:
		t0 = Time.get_ticks_msec()

	var offset: Vector3 = Vector3(pos)
	var base_verts: PackedVector3Array = Cube.precomp_vertices[face]
	
	if base_verts.is_empty():
		#print("precomp_vertices[", face, "] is empty!")
		#print("precomp_vertices keys: ", Cube.precomp_vertices.keys())
		#print("precomp_vertices size: ", Cube.precomp_vertices.size())
		return
	
	var base_norms: PackedVector3Array = Cube.precomp_normals[face]

	var uv_offset: Vector2
	match face:
		Cube.Face.TOP:    uv_offset = block.uv_top
		Cube.Face.BOTTOM: uv_offset = block.uv_bottom
		_:           uv_offset = block.uv_side

	if block.is_transparent:
		for i in 6:
			transparent_vertices.append(base_verts[i] + offset)
		transparent_normals.append_array(base_norms)
		for i in 6:
			var index: int = Cube.FACE_INDICES[face][i / 3][i % 3]
			transparent_uvs.append(
				(Cube.face_vertex_uvs[face][index] + uv_offset) / number_of_textures_in_atlas
			)
	else:
		for i in 6:
			vertices.append(base_verts[i] + offset)
		normals.append_array(base_norms)
		for i in 6:
			var index: int = Cube.FACE_INDICES[face][i / 3][i % 3]
			uvs.append(
				(Cube.face_vertex_uvs[face][index] + uv_offset) / number_of_textures_in_atlas
			)

	if benchmarking:
		face_time += Time.get_ticks_msec() - t0

func commit_mesh() -> void:
	# This used to be the main function that generated chunks. Now it generates the initial chunks
	# and fires a signal when the spawn point is ready.
	commit_visuals()
	EventBus.chunk_manager.request_collision_commit.call_deferred(self)
	var chunk_height = Settings.chunk_height
	
	# This makes sure that the player's spawn point is ready, but doesn't send the signal unless the
	# Surface chunk in that XZ coordinate is the one that's ready.
	if not voxels.is_empty() and \
		int(position.x) == 0 and \
		int(position.z) == 0 and \
		not Settings.player_is_spawned:
		EventBus.spawn_chunk_is_ready.emit()
	
func commit_visuals() -> void:
	if mesh_instance == null:
		return
	
	# Snapshot arrays on the main thread to avoid race conditions with threaded_rebuild
	regen_mutex.lock()
	var snap_vertices := vertices.duplicate()
	var snap_normals := normals.duplicate()
	var snap_uvs := uvs.duplicate()
	var snap_uv2s := uv2s.duplicate()
	var snap_transparent_vertices := transparent_vertices.duplicate()
	var snap_transparent_normals := transparent_normals.duplicate()
	var snap_transparent_uvs := transparent_uvs.duplicate()
	regen_mutex.unlock()

	if snap_vertices.is_empty() and snap_transparent_vertices.is_empty():
		mesh_instance.mesh = null
		return

	var start = Time.get_ticks_msec()
	var new_mesh = ArrayMesh.new()

	if not snap_vertices.is_empty():
		var arrays: Array = []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = snap_vertices
		arrays[Mesh.ARRAY_NORMAL] = snap_normals
		arrays[Mesh.ARRAY_TEX_UV] = snap_uvs
		arrays[Mesh.ARRAY_TEX_UV2] = snap_uv2s
		new_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		new_mesh.surface_set_material(0, material)

	if not snap_transparent_vertices.is_empty():
		var arrays = []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = snap_transparent_vertices
		arrays[Mesh.ARRAY_NORMAL] = snap_transparent_normals
		arrays[Mesh.ARRAY_TEX_UV] = snap_transparent_uvs
		new_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		new_mesh.surface_set_material(new_mesh.get_surface_count() - 1, transparent_material)

	mesh_instance.mesh = new_mesh

	if benchmarking == true:
		print("Commit Visuals: %s ms" % (Time.get_ticks_msec() - start))

# This is to address lag when adding or removing blocks.
func request_rebuild() -> void:
	needs_rebuild = true

# Rebuilds a chunk's mesh in a multithreaded fashion.
func threaded_rebuild() -> void:
	if regen_thread.is_started():
		regen_thread.wait_to_finish()
	var cached_position = position
	regen_thread = Thread.new()
	regen_thread.start(func():
		#print("threaded_rebuild running on chunk at ", cached_position)
		regen_mutex.lock()
		vertices.clear()
		normals.clear()
		uvs.clear()
		transparent_vertices.clear()
		transparent_normals.clear()
		transparent_uvs.clear()
		uv2s.clear()
		generate_mesh()
		regen_mutex.unlock()
		commit_visuals.call_deferred()
		finish_rebuild.call_deferred()
		)

func finish_rebuild() -> void:
	if regen_thread.is_started():
		regen_thread.wait_to_finish()
	is_rebuilding = false

func _exit_tree() -> void:
	if regen_thread.is_started():
		regen_thread.wait_to_finish()
